{"name": "Проверка возвращаемого кода 404 при логине несуществующим курьером", "status": "passed", "start": 1707250004685, "stop": 1707250005151, "uuid": "5afe8a7d-b89d-45a5-b9a0-5ebf69c80f4c", "historyId": "fa25963727f53b3f362cf20a8027a5d7", "testCaseId": "fa25963727f53b3f362cf20a8027a5d7", "fullName": "tests.test_authorization_courier.TestAuthCourier#test_login_nonexistent_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "ANDREY-LAPTOP"}, {"name": "thread", "value": "7944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}