{"name": "Проверка возвращаемого кода 404 при логине несуществующим курьером", "status": "passed", "start": 1707158360862, "stop": 1707158361321, "uuid": "6982e97d-a0af-483f-9807-b152de83b3d5", "historyId": "fa25963727f53b3f362cf20a8027a5d7", "testCaseId": "fa25963727f53b3f362cf20a8027a5d7", "fullName": "tests.test_authorization_courier.TestAuthCourier#test_login_nonexistent_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "ANDREY-LAPTOP"}, {"name": "thread", "value": "9576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}